Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
HTTP GET /student_registration/ 200 [0.01, 127.0.0.1:45532]
HTTP GET /static/jot/form-common.css 200 [0.00, 127.0.0.1:45532]
HTTP GET /static/jot/5e6b428acc8c4e222d1beb91.css 200 [0.00, 127.0.0.1:45542]
HTTP GET /static/jot/prototype.forms.js 200 [0.01, 127.0.0.1:45532]
HTTP GET /static/jot/punycode-1.4.1.min.js 200 [0.01, 127.0.0.1:45552]
HTTP GET /static/jot/math-processor.js 200 [0.01, 127.0.0.1:45568]
HTTP GET /static/jot/validategateways.js 200 [0.01, 127.0.0.1:45570]
HTTP GET /static/jot/jotform.forms.js 200 [0.01, 127.0.0.1:45566]
HTTP GET /static/jot/LOGOFINALFINAL.655e0049d55762.65188587.png 200 [0.00, 127.0.0.1:45594]
HTTP GET /static/jot/smoothscroll.min.js 200 [0.00, 127.0.0.1:45604]
HTTP GET /static/jot/errorNavigation.js 200 [0.00, 127.0.0.1:45552]
Not Found: /student_registration/saved_resource
HTTP GET /student_registration/saved_resource 404 [0.02, 127.0.0.1:45542]
HTTP GET /admin/StakeHolders/teacher/ 200 [0.10, 127.0.0.1:34856]
HTTP GET /static/admin/css/base.css 304 [0.00, 127.0.0.1:34856]
HTTP GET /static/admin/css/responsive.css 304 [0.00, 127.0.0.1:34878]
HTTP GET /static/admin/css/changelists.css 304 [0.01, 127.0.0.1:34874]
HTTP GET /static/admin/css/dark_mode.css 304 [0.01, 127.0.0.1:34856]
HTTP GET /static/admin/js/vendor/jquery/jquery.js 304 [0.01, 127.0.0.1:34884]
HTTP GET /static/admin/css/nav_sidebar.css 304 [0.01, 127.0.0.1:34870]
HTTP GET /static/admin/js/jquery.init.js 304 [0.00, 127.0.0.1:34878]
HTTP GET /static/admin/js/core.js 304 [0.00, 127.0.0.1:34874]
HTTP GET /static/admin/js/actions.js 304 [0.01, 127.0.0.1:34884]
HTTP GET /static/admin/js/urlify.js 304 [0.01, 127.0.0.1:34870]
HTTP GET /static/admin/js/admin/RelatedObjectLookups.js 304 [0.01, 127.0.0.1:34856]
HTTP GET /static/admin/js/prepopulate.js 304 [0.01, 127.0.0.1:34878]
HTTP GET /static/admin/js/vendor/xregexp/xregexp.js 304 [0.01, 127.0.0.1:34874]
HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:34858]
HTTP GET /static/admin/js/theme.js 304 [0.00, 127.0.0.1:34858]
HTTP GET /static/admin/js/nav_sidebar.js 304 [0.00, 127.0.0.1:34874]
HTTP GET /static/admin/js/filters.js 304 [0.00, 127.0.0.1:34874]
HTTP GET /static/admin/img/icon-addlink.svg 304 [0.00, 127.0.0.1:34874]
HTTP GET /static/admin/img/tooltag-add.svg 304 [0.00, 127.0.0.1:34858]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.01, 127.0.0.1:34858]
HTTP GET /admin/StakeHolders/student/ 200 [0.04, 127.0.0.1:34858]
HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:34858]
HTTP GET /admin/StakeHolders/student/72/change/ 200 [0.07, 127.0.0.1:34858]
HTTP GET /static/admin/img/icon-viewlink.svg 304 [0.01, 127.0.0.1:34856]
HTTP GET /static/admin/img/icon-changelink.svg 304 [0.01, 127.0.0.1:34878]
HTTP GET /static/admin/css/forms.css 304 [0.01, 127.0.0.1:34858]
HTTP GET /static/admin/js/prepopulate_init.js 304 [0.00, 127.0.0.1:34858]
HTTP GET /static/admin/css/widgets.css 304 [0.00, 127.0.0.1:34858]
HTTP GET /static/admin/img/icon-deletelink.svg 304 [0.00, 127.0.0.1:34858]
HTTP GET /static/admin/js/change_form.js 304 [0.00, 127.0.0.1:34858]
HTTP GET /admin/jsi18n/ 200 [0.04, 127.0.0.1:34874]
HTTP GET /admin/StakeHolders/student/ 200 [0.04, 127.0.0.1:34874]
HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:34874]
HTTP GET /admin/StakeHolders/student/70/change/ 200 [0.06, 127.0.0.1:34874]
HTTP GET /admin/jsi18n/ 200 [0.02, 127.0.0.1:34874]
HTTP GET /admin/StakeHolders/teacher/ 200 [0.05, 127.0.0.1:34874]
HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:34874]
HTTP GET /admin/StakeHolders/teacher/49/change/ 200 [0.06, 127.0.0.1:34874]
HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:34874]
Unauthorized: /auth/api/login/
HTTP POST /auth/api/login/ 401 [0.22, 127.0.0.1:56960]
HTTP POST /auth/api/login/ 200 [0.23, 127.0.0.1:57120]
HTTP GET /student/get_todays_timetable_for_student?day=friday 200 [0.08, 127.0.0.1:57124]
HTTP GET / 200 [0.01, 127.0.0.1:54860]
HTTP GET / 200 [0.01, 127.0.0.1:43480]
HTTP GET /static/js/main.3d414fa1.js 200 [0.00, 127.0.0.1:43480]
HTTP GET /static/css/main.dc9f2616.css 200 [0.00, 127.0.0.1:43494]
HTTP GET /static/js/8983.bff7a085.chunk.js 200 [0.01, 127.0.0.1:43494]
HTTP GET /static/js/5294.6176c503.chunk.js 200 [0.01, 127.0.0.1:43480]
HTTP GET /static/js/1348.ee323f96.chunk.js 200 [0.01, 127.0.0.1:56828]
HTTP GET /static/js/4846.f6dc87f3.chunk.js 200 [0.01, 127.0.0.1:56816]
HTTP GET /static/js/454.bd2a5452.chunk.js 200 [0.01, 127.0.0.1:56834]
HTTP GET /static/js/3048.74ffe456.chunk.js 200 [0.01, 127.0.0.1:56844]
HTTP GET /static/css/3048.4d2bd59e.chunk.css 200 [0.01, 127.0.0.1:56860]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.02, 127.0.0.1:56832]
HTTP GET /static/css/9063.a8fbdd11.chunk.css 200 [0.01, 127.0.0.1:43494]
HTTP GET /static/js/9063.b7545783.chunk.js 200 [0.01, 127.0.0.1:56868]
HTTP GET /check_server_avaibility/ 200 [0.01, 127.0.0.1:43480]
HTTP GET /static/media/remote-meet.7e638af53944f3764049.png 200 [0.00, 127.0.0.1:43480]
HTTP GET / 200 [0.01, 127.0.0.1:43480]
HTTP GET / 200 [0.01, 127.0.0.1:48032]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.01, 127.0.0.1:48032]
HTTP GET /check_server_avaibility/ 200 [0.01, 127.0.0.1:48046]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.02, 127.0.0.1:48046]
HTTP GET / 200 [0.01, 127.0.0.1:48046]
HTTP GET /api_endpoints/ 200 [0.02, 127.0.0.1:35560]
HTTP GET /api_endpoints/?format=openapi 200 [0.02, 127.0.0.1:35560]
HTTP GET /api_endpoints/?format=openapi 200 [0.02, 127.0.0.1:35568]
HTTP GET / 200 [0.01, 127.0.0.1:60986]
HTTP GET /static/js/main.3d414fa1.js 200 [0.01, 127.0.0.1:60986]
HTTP GET /static/css/main.dc9f2616.css 200 [0.01, 127.0.0.1:60988]
HTTP GET /static/js/4846.f6dc87f3.chunk.js 304 [0.01, 127.0.0.1:60986]
HTTP GET /static/js/8983.bff7a085.chunk.js 304 [0.01, 127.0.0.1:60988]
HTTP GET /static/js/3048.74ffe456.chunk.js 304 [0.01, 127.0.0.1:32768]
HTTP GET /static/js/454.bd2a5452.chunk.js 304 [0.01, 127.0.0.1:32772]
HTTP GET /static/js/1348.ee323f96.chunk.js 304 [0.01, 127.0.0.1:32784]
HTTP GET /static/css/3048.4d2bd59e.chunk.css 304 [0.01, 127.0.0.1:32798]
HTTP GET /static/js/5294.6176c503.chunk.js 304 [0.01, 127.0.0.1:32824]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.02, 127.0.0.1:32810]
HTTP GET /static/css/9063.a8fbdd11.chunk.css 304 [0.00, 127.0.0.1:60986]
HTTP GET /static/js/9063.b7545783.chunk.js 304 [0.00, 127.0.0.1:32840]
HTTP GET /check_server_avaibility/ 200 [0.02, 127.0.0.1:32768]
HTTP GET /static/media/remote-meet.7e638af53944f3764049.png 304 [0.00, 127.0.0.1:32840]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py changed, reloading.
Performing system checks...

November 23, 2023 - 23:49:59
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
<QuerySet [<Schedule: friday>]>
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
HTTP GET / 200 [0.01, 127.0.0.1:48476]
HTTP GET /static/js/main.3d414fa1.js 304 [0.00, 127.0.0.1:48492]
HTTP GET /static/css/main.dc9f2616.css 304 [0.01, 127.0.0.1:48476]
HTTP GET /static/js/5294.6176c503.chunk.js 304 [0.01, 127.0.0.1:48492]
HTTP GET /static/js/4846.f6dc87f3.chunk.js 304 [0.01, 127.0.0.1:48508]
HTTP GET /static/js/8983.bff7a085.chunk.js 304 [0.01, 127.0.0.1:48476]
HTTP GET /static/css/3048.4d2bd59e.chunk.css 304 [0.00, 127.0.0.1:48476]
HTTP GET /static/js/1348.ee323f96.chunk.js 304 [0.00, 127.0.0.1:48508]
HTTP GET /static/js/454.bd2a5452.chunk.js 304 [0.00, 127.0.0.1:48492]
HTTP GET /static/js/3048.74ffe456.chunk.js 200 [0.00, 127.0.0.1:48492]
HTTP GET /static/css/9063.a8fbdd11.chunk.css 304 [0.00, 127.0.0.1:48492]
HTTP GET /static/js/9063.b7545783.chunk.js 200 [0.00, 127.0.0.1:48508]
HTTP GET /static/media/remote-meet.7e638af53944f3764049.png 304 [0.00, 127.0.0.1:48508]
HTTP OPTIONS /check_server_avaibility/ 200 [0.01, 127.0.0.1:48522]
HTTP GET /check_server_avaibility/ 200 [0.01, 127.0.0.1:48522]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.01, 127.0.0.1:48508]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view SMARTROLL.views.student_registration didn't return an HttpResponse object. It returned None instead.
HTTP GET /student_registration/ 500 [0.07, 127.0.0.1:48508]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view SMARTROLL.views.student_registration didn't return an HttpResponse object. It returned None instead.
HTTP GET /student_registration/ 500 [0.03, 127.0.0.1:48508]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view SMARTROLL.views.student_registration didn't return an HttpResponse object. It returned None instead.
HTTP GET /student_registration/ 500 [0.05, 127.0.0.1:48508]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view SMARTROLL.views.student_registration didn't return an HttpResponse object. It returned None instead.
HTTP GET /student_registration/ 500 [0.04, 127.0.0.1:48508]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:35:11
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.08, 127.0.0.1:51806]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.05, 127.0.0.1:51806]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:37:33
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.08, 127.0.0.1:48516]
HTTP GET / 200 [0.01, 127.0.0.1:59960]
HTTP GET /static/js/main.3d414fa1.js 304 [0.00, 127.0.0.1:59960]
HTTP GET /static/css/main.dc9f2616.css 304 [0.00, 127.0.0.1:59964]
HTTP GET /static/js/8983.bff7a085.chunk.js 304 [0.01, 127.0.0.1:59960]
HTTP GET /static/js/4846.f6dc87f3.chunk.js 304 [0.01, 127.0.0.1:59964]
HTTP GET /static/js/5294.6176c503.chunk.js 304 [0.01, 127.0.0.1:59976]
HTTP GET /static/js/454.bd2a5452.chunk.js 304 [0.01, 127.0.0.1:59960]
HTTP GET /static/css/3048.4d2bd59e.chunk.css 304 [0.01, 127.0.0.1:59964]
HTTP GET /static/js/1348.ee323f96.chunk.js 304 [0.00, 127.0.0.1:59980]
HTTP GET /static/js/3048.74ffe456.chunk.js 304 [0.00, 127.0.0.1:59964]
HTTP GET /check_server_avaibility/ 200 [0.01, 127.0.0.1:59964]
HTTP GET /check_token_authenticity/ 200 [0.03, 127.0.0.1:59964]
HTTP GET /static/media/smartroll_logo.a3c3e21d0b4a56919e74.png 304 [0.00, 127.0.0.1:59964]
HTTP GET /static/css/1915.ec1b0949.chunk.css 304 [0.00, 127.0.0.1:59960]
HTTP GET /static/js/1915.bec258b2.chunk.js 304 [0.00, 127.0.0.1:60002]
HTTP GET /manage/get_batches 200 [0.04, 127.0.0.1:59986]
HTTP GET /manage/get_object_counts 200 [0.04, 127.0.0.1:59960]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.06, 127.0.0.1:59960]
Not Found: /favicon.ico
HTTP GET /favicon.ico 404 [0.01, 127.0.0.1:59960]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.04, 127.0.0.1:59960]
HTTP GET / 200 [0.01, 127.0.0.1:59960]
HTTP GET /check_server_avaibility/ 200 [0.01, 127.0.0.1:59960]
HTTP GET /check_token_authenticity/ 200 [0.02, 127.0.0.1:59960]
HTTP GET /manage/get_batches 200 [0.04, 127.0.0.1:59960]
HTTP GET /manage/get_object_counts 200 [0.03, 127.0.0.1:59964]
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 28, in student_registration
    return render(request,'studentregistration.html')
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
HTTP GET /student_registration/ 500 [0.04, 127.0.0.1:48516]
HTTP GET /student_registration/ 200 [0.01, 127.0.0.1:36500]
HTTP GET /static/jot/form-common.css 200 [0.01, 127.0.0.1:36500]
HTTP GET /static/jot/5e6b428acc8c4e222d1beb91.css 200 [0.02, 127.0.0.1:36502]
HTTP GET /static/jot/prototype.forms.js 200 [0.01, 127.0.0.1:36546]
HTTP GET /static/jot/jotform.forms.js 200 [0.03, 127.0.0.1:36500]
HTTP GET /static/jot/punycode-1.4.1.min.js 200 [0.02, 127.0.0.1:36546]
HTTP GET /static/jot/validategateways.js 200 [0.02, 127.0.0.1:36502]
Not Found: /student_registration/{% static "jot/payment_feature.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_feature.css%22%20%7D 404 [0.05, 127.0.0.1:36524]
Not Found: /student_registration/{% static "jot/payment_styles.css" }
Not Found: /student_registration/{% static "jot/donationBox.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_styles.css%22%20%7D 404 [0.06, 127.0.0.1:36514]
HTTP GET /student_registration/%7B%%20static%20%22jot/donationBox.css%22%20%7D 404 [0.06, 127.0.0.1:36536]
HTTP GET /static/jot/math-processor.js 200 [0.01, 127.0.0.1:36546]
HTTP GET /static/jot/LOGOFINALFINAL.655e0049d55762.65188587.png 200 [0.01, 127.0.0.1:36502]
HTTP GET /static/jot/smoothscroll.min.js 200 [0.00, 127.0.0.1:36524]
HTTP GET /static/jot/errorNavigation.js 200 [0.00, 127.0.0.1:36524]
Not Found: /student_registration/saved_resource
HTTP GET /student_registration/saved_resource 404 [0.01, 127.0.0.1:36524]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:37:48
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:41:25
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:42:19
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Forbidden (CSRF token missing.): /student_registration/
HTTP POST /student_registration/ 403 [0.02, 127.0.0.1:46254]
Forbidden (CSRF token missing.): /student_registration/
HTTP POST /student_registration/ 403 [0.01, 127.0.0.1:46254]
HTTP GET /student_registration/ 200 [0.02, 127.0.0.1:46254]
Not Found: /student_registration/{% static "jot/donationBox.css" }
Not Found: /student_registration/{% static "jot/payment_feature.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/donationBox.css%22%20%7D 404 [0.04, 127.0.0.1:41332]
Not Found: /student_registration/{% static "jot/payment_styles.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_feature.css%22%20%7D 404 [0.04, 127.0.0.1:46268]
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_styles.css%22%20%7D 404 [0.04, 127.0.0.1:46254]
Not Found: /student_registration/saved_resource
HTTP GET /student_registration/saved_resource 404 [0.02, 127.0.0.1:41332]
HTTP POST /student_registration/ 200 [0.01, 127.0.0.1:41332]
HTTP GET /student_registration/ 200 [0.01, 127.0.0.1:41332]
Not Found: /student_registration/{% static "jot/payment_styles.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_styles.css%22%20%7D 404 [0.02, 127.0.0.1:41332]
Not Found: /student_registration/{% static "jot/payment_feature.css" }
HTTP GET /student_registration/%7B%%20static%20%22jot/payment_feature.css%22%20%7D 404 [0.02, 127.0.0.1:46254]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:42:21
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
<QueryDict: {'csrfmiddlewaretoken': ['U2EAEWUg3hh9bkt76Yg49WPnFY0xyjCzIE14AjcfqGq4aXf6SaVvzKiRpKEHcn7j'], 'formID': ['233251475582458'], 'jsExecutionTracker': ['build-date-1700773763657=>init-started:1700774000672=>validator-called:1700774000685=>validator-mounted-true:1700774000685=>init-complete:1700774000687=>interval-complete:1700774021686=>init-started:1700804693022=>validator-called:1700804693034=>validator-mounted-true:1700804693035=>interval-existed:1700804693038=>init-complete:1700804693038=>onsubmit-fired:1700804701089=>submit-validation-passed:1700804701102'], 'submitSource': ['form'], 'buildDate': ['1700773763657'], 'q206_name[first]': ['Manav'], 'q206_name[last]': ['Shah'], 'q207_email': ['196330307556.manav.shah@gmail.com'], 'q211_number': ['32323232'], 'q214_phone': ['23232223'], 'website': [''], 'simple_spc': ['233251475582458-233251475582458'], 'timeToSubmit': ['8'], 'event_id': ['1700774000686_233251475582458_m1OBKw1'], 'timeToSubmitExisted': ['20-bfcache-false'], 'validatedNewRequiredFieldIDs': ['{"new":1,"id_206":"Sh","id_207":"19","id_211":"32","id_214":"23"}']}>
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:45:31
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:45:50
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:46:02
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:47:01
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:48:08
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:48:33
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:48:47
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:48:54
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:49:41
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:49:46
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 31
    required_params = ['q206_name[first]', 'q206_name[last]', 'q207_email', 'q211_number','q214_phone','']
IndentationError: unexpected indent
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 31
    required_params = ['q206_name[first]', 'q206_name[last]', 'q207_email', 'q211_number','q214_phone','']
IndentationError: unexpected indent
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:50:05
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:50:17
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:50:32
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:50:43
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:50:47
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:51:03
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:51:18
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:51:35
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:51:37
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:51:46
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:00
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:05
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:14
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:20
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:24
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:37
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:50
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:52:53
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:03
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:05
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:07
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:09
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:14
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:19
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:53:41
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 52
    except Exception as e:
    ^^^^^^
SyntaxError: invalid syntax
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:54:01
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:54:03
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:55:06
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:55:14
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 51
    student_obj.enrollment = student_enrollment
    ^^^^^^^^^^^
SyntaxError: expected 'except' or 'finally' block
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:56:01
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 05:56:23
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration,studet_registration_response
ImportError: cannot import name 'studet_registration_response' from 'SMARTROLL.views' (/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py)
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:01:50
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:02:30
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 53
    except Exception as e:
    ^^^^^^
SyntaxError: invalid syntax
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/daphne/management/commands/runserver.py", line 96, in inner_run
    self.check(display_num_errors=True)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/urls.py", line 22, in <module>
    from .views import check_server_avaibility,check_token_authenticity,student_registration
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py", line 54
    else:
SyntaxError: expected 'except' or 'finally' block
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:02:57
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:03:31
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Internal Server Error: /student_registration/
Traceback (most recent call last):
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/manav1011/Documents/SMARTROLL_SSIP_2023/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view SMARTROLL.views.student_registration didn't return an HttpResponse object. It returned None instead.
HTTP POST /student_registration/ 500 [0.08, 127.0.0.1:37258]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:03:47
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/SMARTROLL/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:04:10
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/Student/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 06:04:16
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
Listen failure: Couldn't listen on 0.0.0.0:8001: [Errno 98] Address already in use.
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/Student/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 09:09:24
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
HTTP GET /student/get_todays_timetable_for_teacher?day=monday 200 [0.14, 127.0.0.1:41138]
/home/manav1011/Documents/SMARTROLL_SSIP_2023/SMARTROLL/Student/views.py changed, reloading.
Performing system checks...

November 24, 2023 - 09:12:14
Django version 4.2.7, using settings 'SMARTROLL.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
[None, None, None, {'slug': '157743_1700771931', 'teacher': OrderedDict([('id', 49), ('profile', OrderedDict([('name', 'Mr. Pragnesh Patel'), ('email', 'Mr.PragneshPatel@gmail.com'), ('ph_no', '7889654123')]))]), 'subject': OrderedDict([('slug', '259573_1700771001'), ('subject_name', 'Python for Data Science'), ('code', 3150713), ('credit', 3), ('semester_number', 5)]), 'classroom': OrderedDict([('slug', '752835_1700305558'), ('class_name', 'CE_106')]), 'start_time': '14:00:00', 'end_time': '15:00:00'}, None, None, None, None, None, None, {'slug': '206070_1700807990', 'teacher': OrderedDict([('id', 44), ('profile', OrderedDict([('name', 'Ms. HETALBEN GEVARIYA'), ('email', 'Ms.HETALBENGEVARIYA@gmail.com'), ('ph_no', '7896541235')]))]), 'subject': OrderedDict([('slug', '181781_1700807289'), ('subject_name', 'Programming for Problem Solving'), ('code', 3110003), ('credit', 4), ('semester_number', 1)]), 'classroom': OrderedDict([('slug', '428503_1700305639'), ('class_name', 'CE_109')]), 'start_time': '15:15:00', 'end_time': '16:15:00'}, None, {'slug': '307555_1700809862', 'teacher': OrderedDict([('id', 45), ('profile', OrderedDict([('name', 'Mr. SUNILKUMAR PATEL'), ('email', 'Mr.SUNILKUMARPATEL@gmail.com'), ('ph_no', '7896541235')]))]), 'subject': OrderedDict([('slug', '573069_1700809475'), ('subject_name', ' Data Structures'), ('code', 3130702), ('credit', 4), ('semester_number', 3)]), 'classroom': OrderedDict([('slug', '968839_1700305653'), ('class_name', 'CE_110')]), 'start_time': '11:30:00', 'end_time': '12:30:00'}, None, None, {'slug': '917836_1700809862', 'teacher': OrderedDict([('id', 49), ('profile', OrderedDict([('name', 'Mr. Pragnesh Patel'), ('email', 'Mr.PragneshPatel@gmail.com'), ('ph_no', '7889654123')]))]), 'subject': OrderedDict([('slug', '573069_1700809475'), ('subject_name', ' Data Structures'), ('code', 3130702), ('credit', 4), ('semester_number', 3)]), 'classroom': OrderedDict([('slug', '492036_1700305422'), ('class_name', 'CE_101')]), 'start_time': '16:15:00', 'end_time': '17:15:00'}, None, None]
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.

System check identified 1 issue (0 silenced).
HTTP GET /student/get_todays_timetable_for_teacher?day=monday 200 [0.09, 127.0.0.1:55262]
HTTP GET /student/get_todays_timetable_for_teacher?day=monday 200 [0.08, 127.0.0.1:55262]
HTTP GET /student/get_todays_timetable_for_teacher?day=monday 200 [0.08, 127.0.0.1:55262]
HTTP GET /api_endpoints/ 200 [0.02, 127.0.0.1:45180]
HTTP GET /api_endpoints/?format=openapi 200 [0.02, 127.0.0.1:45180]
HTTP GET /api_endpoints/?format=openapi 200 [0.02, 127.0.0.1:56202]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.05, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.07, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.08, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.08, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.08, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.09, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.08, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.09, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.10, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.14, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.11, 127.0.0.1:37664]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:37664]
HTTP GET /manage/get_object_counts 200 [0.03, 127.0.0.1:37664]
HTTP GET / 200 [0.01, 127.0.0.1:37664]
HTTP GET /check_server_avaibility/ 200 [0.00, 127.0.0.1:37664]
HTTP GET /check_token_authenticity/ 200 [0.02, 127.0.0.1:37664]
HTTP GET /manage/get_batches 200 [0.03, 127.0.0.1:37664]
HTTP GET /manage/get_object_counts 200 [0.03, 127.0.0.1:43842]
HTTP GET /manage/get_semesters?batch_slug=253155_1700770614 200 [0.05, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.10, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:43842]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.11, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.05, 127.0.0.1:43842]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.05, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.11, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.06, 127.0.0.1:43842]
HTTP POST /manage/timetable/set_lecture_attributes 200 [0.04, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_timetable?semester_slug=171340_1700809302 200 [0.11, 127.0.0.1:43842]
HTTP GET /manage/timetable/get_objects_for_lecture?semester_slug=171340_1700809302 200 [0.07, 127.0.0.1:43842]
